import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider } from 'next-intl';
import viMessages from '../../messages/vi.json';
import enMessages from '../../messages/en.json';
import { cookies } from 'next/headers';
import FloatingContactIcons from "@/components/FloatingContactIcons";
import { DataProvider } from "@/contexts/DataContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const langCookie = cookieStore.get('lang')?.value as 'vi' | 'en' | undefined;
  const locale = langCookie === 'en' ? 'en' : 'vi';
  const messages = locale === 'en' ? enMessages : viMessages;

  return (
    <html lang={locale}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <DataProvider>
            {children}
            <FloatingContactIcons />
          </DataProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
